image: maven

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository/
    - target/
    
stages:
  - build
  - test
  - package 
  - deploy

codebuild:
  tags:
    - build
    - maven
  stage: build
  script: 
    - mvn compile

codetest:
  tags:
    - build
    - maven
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

codepackage:
  tags:
    - build
    - maven
  stage: package
  script:
    - mvn $MAVEN_CLI_OPTS package -Dmaven.test.skip=true
  artifacts:
    paths:
      - target/*.war 

codedeploy:
  tags:
    - maven
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy -Dmaven.test.skip=true